import { createReadStream, promises as fs } from 'node:fs';
import { basename, join, resolve } from 'node:path';
import { createInterface } from 'node:readline';

const REQUIRED_FILES = ['config.json', 'requests.jsonl', 'application.log', 'summary.json'] as const;
const OPERATIONS = ['health', 'product_detail', 'product_search'] as const;
const EXAMPLE_LIMIT = 3;
const MAX_LATENCY_SAMPLES = 10_000;
export type Operation = (typeof OPERATIONS)[number];
export type AnalysisStatus = 'complete' | 'incomplete';

export interface NormalizedEvent { readonly runId: string; readonly requestId: string; readonly operation: Operation; readonly status: number; readonly duration: number; readonly timestamp: string; readonly errorCode?: string; readonly source: { readonly file: string; readonly line: number }; }
export interface AnalysisIssue { readonly code: string; readonly message: string; readonly source?: { readonly file: string; readonly line?: number }; }
export interface Example { readonly requestId: string; readonly operation: Operation; readonly status: number; readonly duration: number; readonly errorCode?: string; readonly source: { readonly file: string; readonly line: number }; }
export interface OperationMetrics { readonly requestCount: number; readonly successCount: number; readonly failureCount: number; readonly errorRate: number; readonly statusCodes: Record<string, number>; readonly errors: Record<string, number>; readonly latencyMs: { readonly average: number; readonly p50: number; readonly p95: number; readonly p99: number; readonly max: number }; readonly throughputRequestsPerSecond: number; }
export interface AnalysisResult {
  readonly schemaVersion: 1; readonly status: AnalysisStatus; readonly runId: string | null; readonly inputDirectory: string; readonly files: Record<string, string>;
  readonly facts: { readonly requestCount: number; readonly successCount: number; readonly failureCount: number; readonly errorRate: number; readonly statusCodes: Record<string, number>; readonly errors: Record<string, number>; readonly durationMs: number; readonly interrupted: boolean };
  readonly metrics: { readonly overall: OperationMetrics; readonly byOperation: Record<Operation, OperationMetrics> };
  readonly examples: { readonly success: Example[]; readonly slow: Example[]; readonly errors: Example[] }; readonly derivedFindings: readonly string[]; readonly hypotheses: readonly string[]; readonly issues: readonly AnalysisIssue[];
  readonly graphify: { readonly status: 'available' | 'unavailable'; readonly evidencePath: string | null; readonly note: string }; readonly dashboardPath: string;
}
interface SummaryInput { schemaVersion: number; status: AnalysisStatus; runId: string; actualRequests: number; durationMs: number; }
interface MutableMetric { durations: number[]; totalDuration: number; maxDuration: number; requestCount: number; successCount: number; failureCount: number; statusCodes: Record<string, number>; errors: Record<string, number>; }

export async function analyzeRun(inputDirectory: string, options: { graphifyEvidencePath?: string } = {}): Promise<AnalysisResult> {
  const directory = resolve(inputDirectory); const issues: AnalysisIssue[] = []; const files: Record<string, string> = Object.fromEntries(REQUIRED_FILES.map((file) => [file, join(directory, file)]));
  const present = await validateRequiredFiles(files, issues); const config = present['config.json'] ? await readJsonFile<Record<string, unknown>>(files['config.json']!, 'config.json', issues) : null; const summary = present['summary.json'] ? await readJsonFile<SummaryInput>(files['summary.json']!, 'summary.json', issues) : null;
  const runId = typeof summary?.runId === 'string' ? summary.runId : typeof config?.runId === 'string' ? config.runId : null; if (summary) validateSummary(summary, issues);
  const metrics = new Map<Operation, MutableMetric>(OPERATIONS.map((operation) => [operation, emptyMetric()])); const overall = emptyMetric(); const examples = { success: [] as Example[], slow: [] as Example[], errors: [] as Example[] }; const requestIds = new Set<string>(); let validEvents = 0;
  if (present['requests.jsonl']) await readEvents(files['requests.jsonl']!, runId, metrics, overall, examples, requestIds, issues, (count) => { validEvents = count; });
  if (present['application.log']) await validateApplicationLog(files['application.log']!, runId, issues);
  if (summary && summary.status !== 'complete') issues.push({ code: 'RUN_INCOMPLETE', message: `summary.json marks run '${summary.runId}' as incomplete.` });
  if (summary && summary.actualRequests !== validEvents) issues.push({ code: 'SUMMARY_COUNT_MISMATCH', message: `summary.json reports ${summary.actualRequests} requests but ${validEvents} valid request records were analyzed.`, source: { file: 'summary.json' } });
  const durationMs = summary?.durationMs ?? 0; const byOperation = Object.fromEntries(OPERATIONS.map((operation) => [operation, finalizeMetric(metrics.get(operation)!, durationMs)])) as Record<Operation, OperationMetrics>; const overallMetric = finalizeMetric(overall, durationMs); const status = issues.length === 0 && validEvents > 0 ? 'complete' : 'incomplete';
  const derivedFindings = status === 'complete' ? deriveFindings(byOperation, overallMetric, examples) : []; const graphifyPath = options.graphifyEvidencePath ? resolve(options.graphifyEvidencePath) : null; const graphifyAvailable = graphifyPath ? await fileExists(graphifyPath) : false;
  return { schemaVersion: 1, status, runId, inputDirectory: directory, files, facts: { requestCount: overallMetric.requestCount, successCount: overallMetric.successCount, failureCount: overallMetric.failureCount, errorRate: overallMetric.errorRate, statusCodes: overallMetric.statusCodes, errors: overallMetric.errors, durationMs, interrupted: summary?.status === 'incomplete' }, metrics: { overall: overallMetric, byOperation }, examples, derivedFindings, hypotheses: graphifyAvailable ? ['The measured search slowdown should be connected to source evidence in the supplied Graphify result.'] : [], issues, graphify: graphifyAvailable ? { status: 'available', evidencePath: graphifyPath, note: 'Graphify evidence was supplied by the caller; inspect its source references before stating a root cause.' } : { status: 'unavailable', evidencePath: null, note: 'code evidence unavailable; measured log analysis is still retained.' }, dashboardPath: join(directory, 'dashboard.html') };
}

async function validateRequiredFiles(files: Record<string, string>, issues: AnalysisIssue[]): Promise<Record<string, boolean>> { const present: Record<string, boolean> = {}; for (const file of REQUIRED_FILES) { present[file] = await fileExists(files[file]!); if (!present[file]) issues.push({ code: 'MISSING_FILE', message: `Required artifact '${file}' is missing.`, source: { file } }); } return present; }
async function readJsonFile<T>(path: string, name: string, issues: AnalysisIssue[]): Promise<T | null> { try { return JSON.parse(await fs.readFile(path, 'utf8')) as T; } catch (error) { issues.push({ code: 'MALFORMED_JSON', message: `Could not parse ${name}: ${error instanceof Error ? error.message : String(error)}`, source: { file: name } }); return null; } }
function validateSummary(summary: SummaryInput, issues: AnalysisIssue[]): void { if (summary.schemaVersion !== 1) issues.push({ code: 'INVALID_SCHEMA', message: 'summary.json schemaVersion must be 1.', source: { file: 'summary.json' } }); for (const field of ['actualRequests', 'durationMs'] as const) if (!Number.isFinite(summary[field]) || summary[field] < 0) issues.push({ code: 'INVALID_SCHEMA', message: `summary.json ${field} must be a non-negative number.`, source: { file: 'summary.json' } }); if (!['complete', 'incomplete'].includes(summary.status)) issues.push({ code: 'INVALID_SCHEMA', message: 'summary.json status must be complete or incomplete.', source: { file: 'summary.json' } }); }

async function readEvents(path: string, runId: string | null, metrics: Map<Operation, MutableMetric>, overall: MutableMetric, examples: { success: Example[]; slow: Example[]; errors: Example[] }, requestIds: Set<string>, issues: AnalysisIssue[], setCount: (count: number) => void): Promise<void> {
  const input = createInterface({ input: createReadStream(path), crlfDelay: Infinity }); let lineNumber = 0; let valid = 0; let sawRecord = false;
  for await (const line of input) { lineNumber += 1; if (!line.trim()) continue; sawRecord = true; let parsed: unknown; try { parsed = JSON.parse(line); } catch (error) { issues.push({ code: 'MALFORMED_JSONL', message: `Invalid JSON on requests.jsonl line ${lineNumber}: ${error instanceof Error ? error.message : String(error)}`, source: { file: 'requests.jsonl', line: lineNumber } }); continue; }
    const event = normalizeEvent(parsed, lineNumber, runId, issues); if (!event || requestIds.has(event.requestId)) { if (event && requestIds.has(event.requestId)) issues.push({ code: 'DUPLICATE_REQUEST_ID', message: `Duplicate requestId '${event.requestId}' was excluded from derived metrics.`, source: event.source }); continue; } requestIds.add(event.requestId); valid += 1; addEvent(event, metrics.get(event.operation)!, overall, examples); setCount(valid);
  }
  if (!sawRecord) issues.push({ code: 'EMPTY_REQUESTS', message: 'requests.jsonl contains no request records.', source: { file: 'requests.jsonl' } });
}
async function validateApplicationLog(path: string, runId: string | null, issues: AnalysisIssue[]): Promise<void> { const input = createInterface({ input: createReadStream(path), crlfDelay: Infinity }); let lineNumber = 0; for await (const line of input) { lineNumber += 1; if (!line.trim() || /\b(?:in)?complete requests=\d+\/\d+$/.test(line)) continue; try { const value = JSON.parse(line) as Record<string, unknown>; if (runId && value.runId !== runId) issues.push({ code: 'RUN_ID_MISMATCH', message: `application.log record runId '${String(value.runId)}' does not match run '${runId}'.`, source: { file: 'application.log', line: lineNumber } }); } catch (error) { issues.push({ code: 'MALFORMED_LOG', message: `Invalid application.log record on line ${lineNumber}: ${error instanceof Error ? error.message : String(error)}`, source: { file: 'application.log', line: lineNumber } }); } } }
function normalizeEvent(value: unknown, line: number, runId: string | null, issues: AnalysisIssue[]): NormalizedEvent | null { const source = { file: 'requests.jsonl', line }; if (!value || typeof value !== 'object') { issues.push({ code: 'INVALID_RECORD', message: 'Request record must be a JSON object.', source }); return null; } const record = value as Record<string, unknown>; const operation = record.operation; const validOperation = typeof operation === 'string' && (OPERATIONS as readonly string[]).includes(operation); const valid = typeof record.runId === 'string' && typeof record.requestId === 'string' && validOperation && typeof record.status === 'number' && Number.isInteger(record.status) && record.status >= 0 && record.status <= 599 && typeof record.duration === 'number' && Number.isFinite(record.duration) && record.duration >= 0 && typeof record.timestamp === 'string'; if (!valid) { issues.push({ code: 'INVALID_RECORD', message: `Invalid request schema at line ${line}; required runId, requestId, operation, status, duration, and timestamp were not valid.`, source }); return null; } if (runId && record.runId !== runId) { issues.push({ code: 'RUN_ID_MISMATCH', message: `Request record runId '${String(record.runId)}' does not match run '${runId}'.`, source }); return null; } return { runId: record.runId as string, requestId: record.requestId as string, operation: operation as Operation, status: record.status as number, duration: record.duration as number, timestamp: record.timestamp as string, ...(typeof record.errorCode === 'string' ? { errorCode: record.errorCode } : {}), source }; }
function emptyMetric(): MutableMetric { return { durations: [], totalDuration: 0, maxDuration: 0, requestCount: 0, successCount: 0, failureCount: 0, statusCodes: {}, errors: {} }; }
function addEvent(event: NormalizedEvent, metric: MutableMetric, overall: MutableMetric, examples: { success: Example[]; slow: Example[]; errors: Example[] }): void { for (const target of [metric, overall]) { target.requestCount += 1; target.totalDuration += event.duration; target.maxDuration = Math.max(target.maxDuration, event.duration); if (target.durations.length < MAX_LATENCY_SAMPLES) target.durations.push(event.duration); else target.durations[target.requestCount % MAX_LATENCY_SAMPLES] = event.duration; target.statusCodes[String(event.status)] = (target.statusCodes[String(event.status)] ?? 0) + 1; } const failed = event.errorCode !== undefined || event.status >= 400 || event.status === 0; if (failed) { for (const target of [metric, overall]) { target.failureCount += 1; const code = event.errorCode ?? `HTTP_${event.status}`; target.errors[code] = (target.errors[code] ?? 0) + 1; } addExample(examples.errors, event); } else { metric.successCount += 1; overall.successCount += 1; addExample(examples.success, event); } if (event.duration >= 100) addExample(examples.slow, event); }
function addExample(target: Example[], event: NormalizedEvent): void { if (target.length < EXAMPLE_LIMIT) target.push({ requestId: event.requestId, operation: event.operation, status: event.status, duration: event.duration, ...(event.errorCode ? { errorCode: event.errorCode } : {}), source: event.source }); }
function finalizeMetric(metric: MutableMetric, durationMs: number): OperationMetrics { const sorted = [...metric.durations].sort((a, b) => a - b); const percentile = (value: number) => sorted.length === 0 ? 0 : sorted[Math.min(sorted.length - 1, Math.ceil(sorted.length * value) - 1)] ?? 0; return { requestCount: metric.requestCount, successCount: metric.successCount, failureCount: metric.failureCount, errorRate: metric.requestCount === 0 ? 0 : Number((metric.failureCount / metric.requestCount).toFixed(4)), statusCodes: metric.statusCodes, errors: metric.errors, latencyMs: { average: metric.requestCount === 0 ? 0 : Number((metric.totalDuration / metric.requestCount).toFixed(2)), p50: percentile(0.5), p95: percentile(0.95), p99: percentile(0.99), max: metric.maxDuration }, throughputRequestsPerSecond: durationMs > 0 ? Number((metric.requestCount / (durationMs / 1_000)).toFixed(2)) : 0 }; }
function deriveFindings(byOperation: Record<Operation, OperationMetrics>, overall: OperationMetrics, examples: { success: Example[]; slow: Example[]; errors: Example[] }): string[] { const findings = [`Analyzed ${overall.requestCount} request events with ${overall.failureCount} failures (${(overall.errorRate * 100).toFixed(2)}% error rate).`]; const search = byOperation.product_search; const detail = byOperation.product_detail; if (search.requestCount > 0 && detail.requestCount > 0 && search.latencyMs.p95 > detail.latencyMs.p95) findings.push(`product_search is the slowest measured operation at p95 ${search.latencyMs.p95} ms versus product_detail at ${detail.latencyMs.p95} ms.`); if (examples.errors.length > 0) findings.push(`Representative failures include ${examples.errors.map((example) => example.errorCode ?? `HTTP_${example.status}`).join(', ')}; inspect the error distribution before inferring a root cause.`); return findings; }
async function fileExists(path: string): Promise<boolean> { try { await fs.access(path); return true; } catch { return false; } }
export function analysisOutputPath(inputDirectory: string): string { return join(resolve(inputDirectory), `${basename(resolve(inputDirectory))}-analysis.json`); }
